# Overrides default rubocop configuration

Style/FrozenStringLiteralComment:
  Description: >-
                 Add the frozen_string_literal comment to the top of files
                 to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
